server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_service
    username: backend_development
    password: U&>RLkVXDK2r%jg5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    redis:
      time-to-live: 60000
      key-prefix: jdj
    cache-name: user
  redis:
    host: localhost
    port: 6379
  config:
    import: optional:configserver:http://localhost:8888
  error:
    include-message: always
jwt:
  issuer: 32mine.net
  secretKey: eedfaa9037130d45d7a9f48f93d92fe1c94c0f1ea0f9d69752efa88abd2e2cc6
  expirationSecond: 3600
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka